### ISSUE TITLE
Crash on changing Area Light Spread 

### ISSUE THREAD

**Issue by Arrovmaker002** [lunadigital/btoa#245] opened 2024-06-29 23:50 UTC
Crash on changing Area Light Spread parameter when ipr is running on GPU. 

Does not occur when using cpu or when still using gpu but ipr is off.

To note: this issue does sometimes cause the autodesk crash reporter screen to appear.

**Comment by osiriswrecks** [comment] 2024-08-19 15:47
Closing, cannot reproduce on latest build. Will revisit if it becomes a problem again.

**Closed by osiriswrecks** 2024-08-19 15:47 UTC
Labels: bug
