### ISSUE TITLE
Camera: Final Render and Render Region Produces Artefacts

### ISSUE THREAD

**Issue by AlexeyAdamitsky** [lunadigital/btoa#108] opened 2021-03-30 07:37 UTC
Blender 2.92
BtoA Dev Branch bd1cdc2
Arnold SDK 6.1.0
Windows 10 2004

Placement of the render region seems to be correct. Yet it produces artifacts on the right side of the region:
![blender_15433YrWt1](https://user-images.githubusercontent.com/64398828/112950889-719ec900-9143-11eb-8d5f-319cbda8df4b.png)

Test scene:
[Arnold_Test_Scene_Camera_Render_Region_GPU.zip](https://github.com/lunadigital/btoa/files/6227242/Arnold_Test_Scene_Camera_Render_Region_GPU.zip)

**Comment by osiriswrecks** [comment] 2021-04-02 13:57
Thanks for catching this @AlexeyAdamitsky. I've noticed this but haven't had the time to log it.

**Comment by AlexeyAdamitsky** [comment] 2021-04-22 08:15
@osiriswrecks I've updated the ticket. The latest 831bd44 updated introduced the same artefacts bug also in the final render.

![image](https://user-images.githubusercontent.com/64398828/115680134-f7392180-a35b-11eb-96f0-56c759c9283c.png)

It looks like the last buckets column get messed up in both final and render region results.

**Comment by osiriswrecks** [comment] 2021-05-21 23:54
Both this issue and issue #117 should now be addressed by commit 6a80c58. When testing, look for the following (these should be fixed now):

- Blender crashes with a "memory access violation" error
- Arnold renders with previous settings (for example, if you change the size of the render region and it seems to render with the old region, or you change the color on the material but it stays the same in the render the next time you render). This began to happen over the past couple of days and it might be related, but I haven't been able to reproduce since fixing the display driver.
- A 1px-tall transparent line appearing at the top or bottom of the render (most often happens with render region enabled)
- Render artifacts (most often appearing on the buckets on the far right of the image)

**Comment by AlexeyAdamitsky** [comment] 2021-05-22 17:40
@osiriswrecks Thank for working on this. I tested it on one of my test scenes. They are simple scenes but I checked on all the possible issues I experienced before and what you mentioned as well. Did have any of the issues discussed here with this build.

**Closed** 2021-05-23 13:54 UTC
Labels: needs qa
